// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Safe_Qr_Backend.Data;

#nullable disable

namespace Safe_Qr_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812071251_AddUrlReportUpdatedAt")]
    partial class AddUrlReportUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Safe_Qr_Backend.Entities.ScanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Results", "Safe_Qr_Backend.Entities.ScanHistory.Results#AggregatedFinalResult", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ServiceResultEnum")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "ServiceScanResult", "Safe_Qr_Backend.Entities.ScanHistory.Results#AggregatedFinalResult.ServiceScanResult#ServiceScanResult", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.PrimitiveCollection<string>("Reasons")
                                        .IsRequired();

                                    b2.Property<string>("ServiceResult")
                                        .IsRequired();

                                    b2.Property<string>("Vendor")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Results")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScanHistory", (string)null);
                });

            modelBuilder.Entity("Safe_Qr_Backend.Entities.ThreatFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportedRiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SystemClassification", "Safe_Qr_Backend.Entities.ThreatFeedback.SystemClassification#AggregatedFinalResult", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ServiceResultEnum")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "ServiceScanResult", "Safe_Qr_Backend.Entities.ThreatFeedback.SystemClassification#AggregatedFinalResult.ServiceScanResult#ServiceScanResult", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.PrimitiveCollection<string>("Reasons")
                                        .IsRequired();

                                    b2.Property<string>("ServiceResult")
                                        .IsRequired();

                                    b2.Property<string>("Vendor")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("SystemClassification")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThreatFeedback", (string)null);
                });

            modelBuilder.Entity("Safe_Qr_Backend.Entities.UrlReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("FlaggedForWrong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Results", "Safe_Qr_Backend.Entities.UrlReport.Results#AggregatedFinalResult", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ServiceResultEnum")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "ServiceScanResult", "Safe_Qr_Backend.Entities.UrlReport.Results#AggregatedFinalResult.ServiceScanResult#ServiceScanResult", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.PrimitiveCollection<string>("Reasons")
                                        .IsRequired();

                                    b2.Property<string>("ServiceResult")
                                        .IsRequired();

                                    b2.Property<string>("Vendor")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("Results")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("UrlReport", (string)null);
                });

            modelBuilder.Entity("Safe_Qr_Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Safe_Qr_Backend.Entities.ScanHistory", b =>
                {
                    b.HasOne("Safe_Qr_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Safe_Qr_Backend.Entities.ThreatFeedback", b =>
                {
                    b.HasOne("Safe_Qr_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
